config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }
  resources :users
  resources :products
  resources :orders, only: [:index, :show, :create, :destroy]
  get 'simple_pages/about'

  get 'simple_pages/contact'

  root 'simple_pages#landing_page'

  get 'simple_pages/index'

  get 'simple_pages/thank_you'
  post 'simple_pages/thank_you'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    can :manage, User, id: user.id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :product
  belongs_to :user
end

app/models/product.rb
class Product < ApplicationRecord
	has_many :orders
	def self.search(search_term)
  		Product.where("name ilike ?", "%#{search_term}%")
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  rescue_from CanCan::AccessDenied do |exception|
  	redirect_to main_app.root_url, alert: exception.message
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @orders = Order.includes(:product).all
  end

  def show
  end

  def new
  end

  def create
  end

  def destroy
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    if params[:q]
      search_term = params[:q]
      @products = Product.search(search_term)
    else
      @products = Product.all
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
    #byebug
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    #byebug
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :href, :genre, :price)
    end
end

app/controllers/simple_pages_controller.rb
class SimplePagesController < ApplicationController
  def index
  end

 # def landing_page
  #	@featured_product = Product.first
 # end

  def landing_page
  	@products = Product.limit(3)
  end

  def redirect_to_back_or_default(default = root_url)
  	respond_to do |format|
	  	format.html { redirect_to_back_or_default }
	  	format.json { render json:
	    	{errors: [I18n.t("some.error.message")]}, status: 404
	  }
		end
  	if request.env["HTTP_REFERER"].present? and request.env["HTTP_REFERER"] != request.env["REQUEST_URI"]
    	redirect_to :back
  	else
    	redirect_to default
  	end
	end

	def thank_you
	  @name = params[:name]
	  @email = params[:email]
	  @message = params[:message]
	  UserMailer.contact_form(@email, @name, @message).deliver_now
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/simple_pages_helper.rb
module SimplePagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/Orders/index.html.erb
<div class="row">
  <% @orders.each do |order| %>
    <div class="col-sm-2 col-md-4">
      <h1>
        Order # <%= order.id %>:
        <%= link_to order.product.name, order.product %>
      </h1>
      <p><%= order.product.description %></p>
      <strong>$ <%= order.product.price %></strong>
    </div><!-- /col -->
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GregsFirstRails</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link src="js/scripts.js"></link>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>

  	<meta name="viewport" content="width=device-width, initial-scale=1">
  	<%= csrf_meta_tags %>
  </head>

  <body class="page-wrap">

  	<nav class="navbar-inverse navbar-fixed-top navbar-collapse">
  	  <ul class="navbar-nav">
        <li><%= link_to "Welcome", root_path %></li>
        <li><%= link_to "Home", simple_pages_index_path %></li>
        <li><%= link_to "About", simple_pages_about_path %></li>
        <li><%= link_to "Contact", simple_pages_contact_path %></li>
        <li><%= link_to "Products", products_path %></li>
        <li><%= link_to "Orders", orders_path %></li>
        <li><%= form_with(url: products_path, id: 'search', method: 'get', local: true) do |form| %>
              <%= form.submit 'Search', id: 'search_button' %>
              <%= form.text_field :q, id: 'q', value: params[:q] %>
            <% end %>      
        </li>
      </ul>
      <ul class="nav pull-right">
        <li>
        <% if user_signed_in? %>
          <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
        <% else %>
          <%= link_to('Login', new_user_session_path) %>
        <% end %>
        </li>
      </ul>
    </nav>   

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>

  	<footer class="site-footer">
  	  &copy; 2017 Tarzan Bros
  	</footer>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container">
    <div class="row">
      <div class="field col-sm-12 col-md-4">
        <%= form.label :name %>
        <%= form.text_field :name, id: :product_name %>
      </div>

      <div class="field col-sm-12 col-md-4">
        <%= form.label :description %>
        <%= form.text_area :description, id: :product_description %>
      </div>

      <div class="field col-sm-12 col-md-4">
        <%= form.label :image_url %>
        <%= form.text_field :image_url, id: :product_image_url %>
      </div>

        <div class="field col-sm-12 col-md-4">
        <%= form.label :href %>
        <%= form.text_field :href, id: :product_href %>
      </div>

       <div class="field col-sm-12 col-md-4">
        <%= form.label :genre %>
        <%= form.text_field :genre, id: :product_genre %>
      </div>

      <div class="field col-sm-12 col-md-4">
        <%= form.label :price %>
        <%= form.text_field :price, id: :product_price %>
      </div>

      <div class="actions">
        <%= form.submit %>
      </div>
    </div>
  </div>

<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<title>Products</title>

<p id="notice"><%= notice %></p>
<h1>Products</h1>

<div class="container products">
  <div class="row">
    <% @products.each do |current_product| %>
    <%= render partial: "shared/product_item", locals: {product1: current_product} %>
    <% end %>
  </div>
</div>

<br>
<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= image_tag(@product.image_url) %>
</p>

<p>
  <strong>Href:</strong>
  <%= @product.href %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @product.genre %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %> CHF
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/shared/_homepage_item.html.erb
	<div class="covers">
		<%= link_to image_tag("album cover.jpg", size: "100", class: "img-responsive", title: 'Apartheid of thoughts'), "https://tarzanbros.bandcamp.com/album/apartheid-of-thoughts" %>
		<%= link_to image_tag("chess.jpg", size: "100", class: "img-responsive", title: 'Chess with your life' ), "https://tarzanbros.bandcamp.com/album/chess-with-your-life" %>
		<%= link_to image_tag("reborn.jpg", size: "100", class: "img-responsive", title: 'Reborn' ), "https://tarzanbros.bandcamp.com/track/reborn" %>
		<%= link_to image_tag("malecon.jpg", size: "100", class: "img-responsive", title: 'Malecon' ), "https://tarzanbros.bandcamp.com/track/oh-malecon" %>
		<%= link_to image_tag("jerry.jpg", size: "100", class: "img-responsive", title: 'Jerry' ), "https://tarzanbros.bandcamp.com/track/jerry-tarzanbros-remix" %>
		<%= link_to image_tag("tomato.jpg", size: "100", class: "img-responsive", title: "Don't touch me tomato" ), "https://tarzanbros.bandcamp.com/track/dont-touch-me-tomato-phyllis-dillon-tarzan-bros-remix" %>
		<%= link_to image_tag("skanville.jpg", size: "100", class: "img-responsive", title: 'Train to skanville' ), "https://tarzanbros.bandcamp.com/track/ethiopians-train-to-skaville-tarzanbros-remix" %>
		<%= link_to image_tag("diggin.jpg", size: "100", class: "img-responsive", title: 'B-hop diggin' ), "https://tarzanbros.bandcamp.com/track/b-hop-diggin" %>
		<%= link_to image_tag("zealots.jpg", size: "100", class: "img-responsive", title: 'Zealots' ), "https://tarzanbros.bandcamp.com/track/fugees-zealots-tarzan-bros-re-imagined" %>
		<%= link_to image_tag("imperial.jpg", size: "100", class: "img-responsive", title: 'Imperial bros' ), "https://tarzanbros.bandcamp.com/album/imperial-bros" %>
	</div>

app/views/shared/_product_item.html.erb
<div class="col-md-4 col-sm-6 col-xs-12">
  <a href="<%= product1.href %>"><h3><%= product1.name %></h3></a>
  <p><%= image_tag(product1.image_url, class:"img-responsive", size: "300") %></p>
  <p class="description"><%= product1.description %></p><p class="genre">/<%= product1.genre %>/</p><strong><%= product1.price %> CHF</strong>
  <br>
  <p class="show"><%= link_to 'Show', product1 %></p>
  <p class="edit"><%= link_to 'Edit', edit_product_path(product1) %></p>
  <p class="destroy"><%= link_to 'Destroy', product1, method: :delete, data: { confirm: 'Are you sure?' } %></p>
</div>

app/views/simple_pages/about.html.erb
<div class="container about">

	<h1>Who we are</h1>
	<p>Tarzan Bros are the brain brothers of Greg and Theo Tantanozis, a complex of composing, producing and performing all in one exclusive Reggae Hip - Hop mixture!</p>
	<h1>What's this app</h1>
	<p>Here you can buy online our music, order your own ideas, edited and produced by our little family or play the TB coin and be the one who travels with us on our next tour</p>

</div>

app/views/simple_pages/contact.html.erb
<div class="container">

	<h1>Get in touch</h1>

	<div class="row">

		<div class="col-md-4 col-sm-12 contact-form">
			<%= flash[:notice] %>

			<%= form_with(url:"/simple_pages/thank_you", method: "post", local: true) do |form| %>
			  <div class="form-group">
			    <%= form.label :name, class: "contact-form-titles" %>
			    <%= form.text_field :name, class: "form-control", placeholder: "Enter Name", :required => true %>
			  </div>
			  <div class="form-group">
			    <%= form.label :email, class: "contact-form-titles" %>
			    <%= form.text_field :email, class: "form-control", placeholder: "Enter Email", :required => true, :pattern => '[^@]+@[^@]+\.[a-zA-Z]{2,6}' %>
			  </div>
			  <div class="form-group">
			    <%= form.label :message, class: "contact-form-titles" %>
			    <%= form.text_area :message, class: "form-control", placeholder: "Enter Message", rows: 5 %>
			  </div>
			<%= form.submit "Send", class: "form_label" %>
			<% end %>
		</div>
	
	
		<div class="col-md-4 contact-details">
			<p>Daily 9:00 - 18:00 <br> +41 (0) 76 689 26 16 <br> tarzanbros@gmail.com <br> Austrasse 40 <br> 8953 Dietikon <br> Switzerland</p>
		</div>

		<div class="col-md-4 maps">
			Here we'll put the MAP!
		</div>
	</div>
</div>

app/views/simple_pages/index.html.erb
<div class="container full-home">

	<div class="headers-home">
		<h1>Welcome to the Tarzan Bros family</h1>
	
		<h2>Get a tune or let us write a song for you</h2>
	</div>

	<div class="covers">
		<%= link_to image_tag("album cover.jpg", size: "100", class: "img-responsive", title: 'Apartheid of thoughts'), "https://tarzanbros.bandcamp.com/album/apartheid-of-thoughts" %>
		<%= link_to image_tag("chess.jpg", size: "100", class: "img-responsive", title: 'Chess with your life' ), "https://tarzanbros.bandcamp.com/album/chess-with-your-life" %>
		<%= link_to image_tag("reborn.jpg", size: "100", class: "img-responsive", title: 'Reborn' ), "https://tarzanbros.bandcamp.com/track/reborn" %>
		<%= link_to image_tag("malecon.jpg", size: "100", class: "img-responsive", title: 'Malecon' ), "https://tarzanbros.bandcamp.com/track/oh-malecon" %>
		<%= link_to image_tag("jerry.jpg", size: "100", class: "img-responsive", title: 'Jerry' ), "https://tarzanbros.bandcamp.com/track/jerry-tarzanbros-remix" %>
		<%= link_to image_tag("tomato.jpg", size: "100", class: "img-responsive", title: "Don't touch me tomato" ), "https://tarzanbros.bandcamp.com/track/dont-touch-me-tomato-phyllis-dillon-tarzan-bros-remix" %>
		<%= link_to image_tag("skanville.jpg", size: "100", class: "img-responsive", title: 'Train to skanville' ), "https://tarzanbros.bandcamp.com/track/ethiopians-train-to-skaville-tarzanbros-remix" %>
		<%= link_to image_tag("diggin.jpg", size: "100", class: "img-responsive", title: 'B-hop diggin' ), "https://tarzanbros.bandcamp.com/track/b-hop-diggin" %>
		<%= link_to image_tag("zealots.jpg", size: "100", class: "img-responsive", title: 'Zealots' ), "https://tarzanbros.bandcamp.com/track/fugees-zealots-tarzan-bros-re-imagined" %>
		<%= link_to image_tag("imperial.jpg", size: "100", class: "img-responsive", title: 'Imperial bros' ), "https://tarzanbros.bandcamp.com/album/imperial-bros" %>
	</div>

</div>

<div class="date-home">
	<p><%= Time.now %></p>
</div>

app/views/simple_pages/landing_page.html.erb
<div class="container-fluid" id="landing-page-carousel">

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <% @products.length.times do |i, index| %>
      <li data-target="#carousel-example-generic" data-slide-to="<%= i %>" <%= "class=active" if i == 0 %>></li>
    <% end %>
  </ol> 

  <div class="carousel-inner" role="listbox">
    <% @products.all.each_with_index do |product, index| %>
    <div class="carousel-item <%= ' active' if index == 0 %>">
      <%= link_to image_tag(product.image_url, class: 'img-fluid') %>
    </div>      
    <% end %>
  </div>

  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
  <%= params[:example_key].to_i * 10 %>

app/views/simple_pages/thank_you.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <p>Thank you. We have received your message and will respond as soon as possible.</p>
    
   	<%= link_to "Back to Contact", simple_pages_contact_path %>
  </div><!-- / panel-body -->
</div><!-- / panel -->

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, id: :user_first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, id: :user_last_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>